-- Seed Data: AI Interview Coach (Cindy from Cinder)
-- Created: 2025-10-26
-- Purpose: Generic soft-skill question bank and system configuration

-- ============================================================================
-- SYSTEM CONFIGURATION
-- ============================================================================

INSERT INTO system_config (key, value) VALUES
    ('audio_mode_enabled', 'true'),
    ('monthly_cost_threshold_usd', '285.00'),
    ('max_sessions_per_day', '2'),
    ('max_questions_per_session', '10'),
    ('current_terms_version', 'v1.0'),
    ('current_privacy_version', 'v1.0')
ON CONFLICT (key) DO NOTHING;

-- ============================================================================
-- GENERIC SOFT-SKILL QUESTION BANK
-- ============================================================================
-- Note: Generic questions are NOT stored in the database
-- They will be defined in the application code (lib/data/question-bank.ts)
-- and selected/inserted when a session is created
--
-- This approach avoids the complexity of maintaining a separate question_bank table
-- while still providing reusable generic questions for guest sessions

-- ============================================================================
-- SAMPLE JOB POSTINGS (for testing job digest)
-- ============================================================================

INSERT INTO jobs (
    id,
    source,
    title,
    company,
    skills,
    must_have_skills,
    seniority_level,
    location,
    posting_url,
    active
) VALUES
    (
        gen_random_uuid(),
        'cinder',
        'Senior Full Stack Engineer',
        'Cinder AI',
        ARRAY['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'Next.js', 'REST APIs', 'Git'],
        ARRAY['TypeScript', 'React', 'Node.js'],
        'senior',
        'Portland, OR',
        'https://teamcinder.com/careers/senior-full-stack',
        TRUE
    ),
    (
        gen_random_uuid(),
        'cinder',
        'Product Manager - AI Tools',
        'Cinder AI',
        ARRAY['Product Management', 'AI/ML', 'User Research', 'Roadmap Planning', 'Agile'],
        ARRAY['Product Management', 'AI/ML'],
        'mid',
        'Remote',
        'https://teamcinder.com/careers/product-manager-ai',
        TRUE
    ),
    (
        gen_random_uuid(),
        'ziprecruiter',
        'Software Engineer',
        'Tech Startup Inc',
        ARRAY['Python', 'Django', 'PostgreSQL', 'Docker', 'AWS'],
        ARRAY['Python', 'Django'],
        'mid',
        'San Francisco, CA',
        'https://example.com/jobs/software-engineer-12345',
        TRUE
    );

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE questions IS
    'Questions are created per session. Generic soft-skill questions are stored in application code and inserted when a guest session starts. Tailored questions are generated by OpenAI for registered users with resumes.';

COMMENT ON COLUMN questions.is_gentle IS
    'Gentle questions are preferred for Low-Anxiety Mode sessions (less intimidating phrasing).';

COMMENT ON TABLE system_config IS
    'Feature flags and system-wide configuration. Updated dynamically by application (e.g., audio_mode_enabled toggled when cost threshold reached).';
